テキストの目的
・数式演算ライブラリのNumPyに慣れる
・行列演算に慣れる

行列積の計算を手計算で行った後、スクラッチ実装することで理解を深める。

2.行列積

【問題1】行列積を手計算する

A = (-1, 2, 3)   B = (0, 2, 1)
    ( 4,-5, 6)       (0, 2,-8)
    ( 7, 8,-9)       (2, 9,-1)
       
AB = (a11,a12,a13) 
      (a21,a22,a23)
      (a31,a32,a33)
    = (6,29,-20) 
      (12,52,38)
      (-18,-51,-48)
      
以下、計算過程
a11 = -1×0 + 2×0 + 3×2 = 6,
a12 = -1×2 + 2×2 + 3×9 = 29,
a13 = -1×1 + 2×-8 + 3×-1 = -20,
a21 =  4×0 + (-5×0) + 6×2 = 12,
a22 =  4×2 + (-5×2) + 6×9 = 52,
a23 =  4×1 + (-5×-8) + 6×-1 = 38,
a31 =  7×0 + 8×0 + (-9×2) = -18,
a12 =  7×2 + 8×2 + (-9×9) = -51,
a13 =  7×1 + 8×-8 + (-9×-1) = -48,

【問題2】NumPyの関数による計算

In [10]:
import numpy as np

a_ndarray = np.array([[-1,2,3],
                      [4,-5,6],
                      [7,8,-9]])

b_ndarray = np.array([[0,2,1],
                      [0,2,-8],
                      [2,9,-1]])

print(a_ndarray@b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装

In [11]:
ab11 = []

for i in range(3):
    tmp = 0
    tmp += a_ndarray[0,i]*b_ndarray[i,0]
    print(a_ndarray[0,i],"×",b_ndarray[i,0],
          "=",a_ndarray[0,i]*b_ndarray[i,0])
ab11.append(tmp)
print("Σ=",ab11[0])

-1 × 0 = 0
2 × 0 = 0
3 × 2 = 6
Σ= 6


【問題4】行列積を行う関数の作成

In [14]:
# 行列の計算をスクラッチ実装する

def maltpul(a,b):
    
    n,m = a.shape
    p,q = b.shape
    
    ans = np.array([])
    
    assert m == p,"Error : can not calcuration >> m ≠ p "
    
    for i in range(n):
        for j in range(q):
            tmp = a[i,:]*b[:,j]
            ans = np.append(ans,tmp.sum())
                
    ans = ans.reshape(n,q)
    
    return ans

print(maltpul(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


4.行列積が定義されない組み合わせの行列

【問題5】計算が定義されない入力を判定する

In [15]:
d_ndarray = np.array([[-1, 2, 3],
                       [4, -5, 6]])

e_ndarray = np.array([[-9, 8, 7],
                      [6, -5, 4]])

print(d_ndarray.shape)
print(e_ndarray.shape)
print(maltpul(d_ndarray,e_ndarray))

(2, 3)
(2, 3)


AssertionError: Error : can not calcuration >> m ≠ p 

In [16]:
e_ndarray = e_ndarray.T
print(d_ndarray.shape)
print(e_ndarray.shape)
print(maltpul(d_ndarray,e_ndarray))

(2, 3)
(3, 2)
[[ 46.  -4.]
 [-34.  73.]]


検算

In [17]:
print(d_ndarray@e_ndarray)

[[ 46  -4]
 [-34  73]]
